import { createHash, randomUUID } from "node:crypto";
import { createReadStream, existsSync } from "node:fs";
import { createServer } from "node:http";
import { extname, join, normalize } from "node:path";

const port = Number(process.env.PORT ?? 3000);
const publicDirectory = join(process.cwd(), "public");
const rooms = new Map();
const clients = new Set();
const startingModels = [["iron-1", "Ironclad", "#8da3b8", 26, 31], ["iron-2", "Sparrow", "#c4d3df", 38, 48], ["iron-3", "Wayfarer", "#728ca7", 24, 66], ["ember-1", "Ember", "#d58359", 74, 30], ["ember-2", "Ashen", "#f0b16e", 64, 52], ["ember-3", "Kindler", "#a85942", 77, 68]].map(([id, name, color, x, y]) => ({ id, name, color, x, y }));
function getRoom(id) { if (!rooms.has(id)) rooms.set(id, structuredClone(startingModels)); return rooms.get(id); }
function send(socket, value) { if (socket.destroyed || !socket.writable) return; const data = Buffer.from(JSON.stringify(value)); const header = data.length < 126 ? Buffer.from([129, data.length]) : Buffer.from([129, 126, data.length >> 8, data.length & 255]); socket.write(Buffer.concat([header, data])); }
function broadcast(roomId, value) { for (const client of clients) if (client.roomId === roomId) send(client.socket, value); }
function playerCount(roomId) { return [...clients].filter((client) => client.roomId === roomId).length; }
function parseFrames(socket, onMessage) { let input = Buffer.alloc(0); socket.on("data", (chunk) => { input = Buffer.concat([input, chunk]); while (input.length >= 6) { const length = input[1] & 127; if (length > 125 || input.length < length + 6) return; const mask = input.subarray(2, 6); const data = input.subarray(6, length + 6); for (let i = 0; i < data.length; i += 1) data[i] ^= mask[i % 4]; input = input.subarray(length + 6); onMessage(data.toString()); } }); }
const mime = { ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8" };
const server = createServer((request, response) => { const pathname = request.url.split("?")[0]; const path = normalize(join(publicDirectory, pathname === "/" ? "index.html" : pathname)); if (!path.startsWith(publicDirectory) || !existsSync(path)) return response.writeHead(404).end("Not found"); response.writeHead(200, { "content-type": mime[extname(path)] ?? "application/octet-stream" }); createReadStream(path).pipe(response); });
server.on("upgrade", (request, socket) => { const roomId = new URL(request.url, `http://${request.headers.host}`).searchParams.get("room")?.replace(/[^a-zA-Z0-9-]/g, "").slice(0, 40) || randomUUID(); const key = request.headers["sec-websocket-key"]; if (!key) return socket.destroy(); const accept = createHash("sha1").update(`${key}258EAFA5-E914-47DA-95CA-C5AB0DC85B11`).digest("base64"); socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\n\r\n`); const client = { socket, roomId }; clients.add(client); socket.on("error", () => clients.delete(client)); send(socket, { type: "room", roomId, models: getRoom(roomId) }); broadcast(roomId, { type: "presence", count: playerCount(roomId) }); parseFrames(socket, (raw) => { try { const message = JSON.parse(raw); const model = getRoom(roomId).find((entry) => entry.id === message.id); if (message.type !== "move" || !model || !Number.isFinite(message.x) || !Number.isFinite(message.y)) return; model.x = Math.max(2, Math.min(98, message.x)); model.y = Math.max(2, Math.min(98, message.y)); broadcast(roomId, { type: "state", models: getRoom(roomId) }); } catch {} }); socket.on("close", () => { clients.delete(client); broadcast(roomId, { type: "presence", count: playerCount(roomId) }); }); });
server.listen(port, () => console.log(`Mistboard is running at http://localhost:${port}`));
