import React,{useEffect,useRef,useState}from"react";import{createRoot}from"react-dom/client";import*as Popover from"@radix-ui/react-popover";import{Check,ChevronDown}from"lucide-react";import"./styles.css";
const sizes=Array.from({length:20},(_,i)=>i+1),BOARD_INCHES=36,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function CircleSelect({disabled,values,onChange}){return <Popover.Root><Popover.Trigger asChild><button className="control" disabled={disabled}>{values.length?values.map(v=>`${v}″`).join(", "):"Circles"}<ChevronDown size={14}/></button></Popover.Trigger><Popover.Portal><Popover.Content className="menu" align="end"><button className="option clear" onClick={()=>onChange([])}>Clear</button>{sizes.map(v=><button className="option" key={v} onClick={()=>onChange(values.includes(v)?values.filter(x=>x!==v):[...values,v])}>{v}″ {values.includes(v)&&<Check size={14}/>}</button>)}</Popover.Content></Popover.Portal></Popover.Root>}
function App(){const[models,setModels]=useState([]),[selected,setSelected]=useState(null),[circles,setCircles]=useState({}),[zoom,setZoom]=useState(1),[measuring,setMeasuring]=useState(false),[ruler,setRuler]=useState(null),sock=useRef(),board=useRef();const model=models.find(m=>m.id===selected),send=m=>sock.current?.readyState===1&&sock.current.send(JSON.stringify(m));
useEffect(()=>{const room=new URL(location).searchParams.get("room"),ws=sock.current=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}/socket${room?`?room=${room}`:""}`);ws.onmessage=({data})=>{const m=JSON.parse(data);if(m.models)setModels(m.models);if(m.roomId)history.replaceState({},"",`?room=${m.roomId}`)};return()=>ws.close()},[]);
const update=(id,patch,type="move")=>setModels(ms=>ms.map(m=>m.id===id?({...m,...patch}):m));const rotate=d=>{if(!model)return;const rotation=((model.rotation||0)+d+360)%360;update(model.id,{rotation});send({type:"rotate",id:model.id,rotation})};
useEffect(()=>{const key=e=>{if(!model)return;const s=(e.shiftKey?0.5:1)/BOARD_INCHES*100,r=(model.rotation||0)*Math.PI/180;if(e.key==="ArrowLeft")rotate(-15);else if(e.key==="ArrowRight")rotate(15);else if(e.key==="ArrowUp"){const x=clamp(model.x+Math.sin(r)*s,2,98),y=clamp(model.y-Math.cos(r)*s,2,98);update(model.id,{x,y});send({type:"move",id:model.id,x,y,rotation:model.rotation||0})}else if(e.key==="ArrowDown"){const x=clamp(model.x-Math.sin(r)*s,2,98),y=clamp(model.y+Math.cos(r)*s,2,98);update(model.id,{x,y});send({type:"move",id:model.id,x,y,rotation:model.rotation||0})}else return;e.preventDefault()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[model]);
const point=e=>{const r=board.current.getBoundingClientRect();return{x:clamp((e.clientX-r.left)/r.width*100,0,100),y:clamp((e.clientY-r.top)/r.height*100,0,100)}};
const down=(e,m)=>{if(measuring){const p=point(e);setRuler({a:p,b:p});const move=x=>setRuler(q=>({...q,b:point(x)})),up=()=>{window.removeEventListener("pointermove",move);setMeasuring(false)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true});return}setSelected(m.id);let latest={x:m.x,y:m.y};const move=x=>{latest=point(x);update(m.id,latest);send({type:"move",id:m.id,x:latest.x,y:latest.y,rotation:m.rotation||0})},up=()=>{window.removeEventListener("pointermove",move);send({type:"move",id:m.id,x:latest.x,y:latest.y,rotation:m.rotation||0})};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true})};
const values=model?circles[model.id]||[]:[];return <main><header><div><p>SHARED ONLINE TABLETOP</p><h1>Mistboard</h1></div><div>● Live board</div></header><section className="table"><div className="tools"><button className="control" onClick={()=>setZoom(z=>clamp(z-.2,.6,2.5))}>−</button><button className="control" onClick={()=>setZoom(z=>clamp(z+.2,.6,2.5))}>+</button><button className="control" onClick={()=>setZoom(1)}>Reset view</button><button className={`control ${measuring?"active":""}`} onClick={()=>setMeasuring(v=>!v)}>Measure</button><CircleSelect disabled={!model} values={values} onChange={v=>setCircles({...circles,[model.id]:v})}/></div><div ref={board} className={`board `} onPointerDown={e=>{if(measuring)down(e,{})}} onWheel={e=>{e.preventDefault();setZoom(z=>clamp(z*(e.deltaY<0?1.1:.9),.6,2.5))}} style={{transform:`scale(${zoom})`}}>{ruler&&<><svg className="ruler" viewBox="0 0 100 100"><line x1={ruler.a.x} y1={ruler.a.y} x2={ruler.b.x} y2={ruler.b.y}/></svg><b className="ruler-label" style={{left:`${(ruler.a.x+ruler.b.x)/2}%`,top:`${(ruler.a.y+ruler.b.y)/2}%`}}>{(Math.hypot(ruler.a.x-ruler.b.x,ruler.a.y-ruler.b.y)*.36).toFixed(1)}″</b></>}{Object.entries(circles).flatMap(([id,vs])=>{const m=models.find(x=>x.id===id);return m?vs.map(v=><div className="circle" style={{left:`${m.x}%`,top:`${m.y}%`,width:`${(v*2+((m.baseMm??30)/25.4))/BOARD_INCHES*100}%`,height:`${(v*2+((m.baseMm??30)/25.4))/BOARD_INCHES*100}%`}} key={`${id}-${v}`}/>):[]})}{models.map(m=><button className={`model ${selected===m.id?"selected":""}`} onPointerDown={e=>down(e,m)} style={{left:`${m.x}%`,top:`${m.y}%`,width:`${((m.baseMm??30)/25.4/BOARD_INCHES*100)}%`,height:`${((m.baseMm??30)/25.4/BOARD_INCHES*100)}%`,background:m.color,"--rotation":`${m.rotation||0}deg`}} key={m.id}>{m.name[0]}</button>)}</div></section><footer>{model?<><span>Selected: {model.name} · {Math.round(model.rotation||0)}° <select value={model.baseMm??30} onChange={e=>{const baseMm=Number(e.target.value);update(model.id,{baseMm});send({type:"base",id:model.id,baseMm})}}><option value="30">30 mm</option><option value="40">40 mm</option><option value="50">50 mm</option></select></span><span><button onClick={()=>rotate(-15)}>↶</button><button onClick={()=>rotate(15)}>↷</button></span></>:"Select a model"}<span>36″ × 36″</span></footer></main>}
createRoot(document.getElementById("root")).render(<App/>);
