import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import*as Popover from"@radix-ui/react-popover";
import{Check,ChevronDown}from"lucide-react";
import{Application,Graphics,Text}from"pixi.js";
import{BOARD_INCHES,baseDiameterInches,chargeLanePoints,clamp,inchesToPixels,percentToPixels}from"./geometry.js";
import"./styles.css";

const sizes=Array.from({length:20},(_,i)=>i+1);
function CircleSelect({disabled,values,onChange}){return <Popover.Root><Popover.Trigger asChild><button className="control" disabled={disabled}>{values.length?values.map(v=>`${v}″`).join(", "):"Circles"}<ChevronDown size={14}/></button></Popover.Trigger><Popover.Portal><Popover.Content className="menu" align="end"><button className="option clear" onClick={()=>onChange([])}>Clear</button>{sizes.map(v=><button className="option" key={v} onClick={()=>onChange(values.includes(v)?values.filter(x=>x!==v):[...values,v])}>{v}″ {values.includes(v)&&<Check size={14}/>}</button>)}</Popover.Content></Popover.Portal></Popover.Root>}

function PixiBoard({models,selected,circles,chargeId,measuring,ruler,zoom,onSelect,onMove,onRotate,onMeasure}){
  const host=useRef(null),state=useRef({});state.current={...state.current,models,selected,circles,chargeId,measuring,ruler,zoom,onSelect,onMove,onRotate,onMeasure};
  useEffect(()=>{state.current.draw?.()});
  useEffect(()=>{let app,observer,disposed=false;
    const start=async()=>{app=new Application();await app.init({background:0x789e78,antialias:true,autoDensity:true,resolution:window.devicePixelRatio||1});if(disposed){app.destroy();return}host.current.appendChild(app.canvas);app.canvas.className="pixi-canvas";app.canvas.addEventListener("contextmenu",e=>e.preventDefault());
      const point=e=>{const box=app.canvas.getBoundingClientRect();return{x:clamp((e.clientX-box.left)/box.width*100,0,100),y:clamp((e.clientY-box.top)/box.height*100,0,100)}};
      const drag=(model,event)=>{let latest={x:model.x,y:model.y};const move=e=>{latest=point(e);state.current.onMove(model.id,latest)},up=()=>{window.removeEventListener("pointermove",move);state.current.onMove(model.id,latest)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up,{once:true})};
      const turn=(model,event)=>{const box=app.canvas.getBoundingClientRect(),center={x:box.left+box.width*model.x/100,y:box.top+box.height*model.y/100},angle=e=>Math.round((((Math.atan2(e.clientX-center.x,-(e.clientY-center.y))*180/Math.PI+360)%360)*2))/2,move=e=>state.current.onRotate(model.id,angle(e));window.addEventListener("mousemove",move);window.addEventListener("mouseup",()=>window.removeEventListener("mousemove",move),{once:true})};
      const measure=event=>{const start=point(event),move=e=>state.current.onMeasure({a:start,b:point(e)});state.current.onMeasure({a:start,b:start});window.addEventListener("pointermove",move);window.addEventListener("pointerup",()=>{window.removeEventListener("pointermove",move);state.current.onMeasure(undefined)},{once:true})};
      const draw=()=>{if(!app||disposed)return;const s=state.current,box=host.current.getBoundingClientRect(),side=Math.max(1,Math.min(box.width,box.height));app.renderer.resize(side,side);app.stage.removeChildren();const px=percentToPixels(side),inches= inchesToPixels(side),add=g=>(app.stage.addChild(g),g);
        const background=add(new Graphics().rect(0,0,side,side).fill(0x789e78));background.eventMode="static";background.cursor=s.measuring?"crosshair":"default";background.on("pointerdown",e=>{if(s.measuring){measure(e.nativeEvent);return}if(e.button===2&&s.selected){const model=s.models.find(m=>m.id===s.selected);if(model)turn(model,e.nativeEvent);return}if(e.button===0){s.onSelect(null);s.onMeasure(null)}});
        const grid=add(new Graphics());for(let i=0;i<=8;i++){const v=side*i/8;grid.moveTo(v,0).lineTo(v,side).moveTo(0,v).lineTo(side,v)}grid.stroke({color:0x436d54,alpha:.55,width:1});
        const charge=s.models.find(m=>m.id===s.chargeId);if(charge){const points=chargeLanePoints(charge,10).flatMap(p=>[px(p.x),px(p.y)]);add(new Graphics().poly(points,true).fill({color:0xf0dc88,alpha:.22}).stroke({color:0xf0dc88,alpha:.8,width:1}))}
        Object.entries(s.circles).forEach(([id,values])=>{const model=s.models.find(m=>m.id===id);if(!model)return;values.forEach(range=>{const x=px(model.x),y=px(model.y),radius=inches(range+baseDiameterInches(model)/2);add(new Graphics().circle(x,y,radius).fill({color:0xf0dc88,alpha:.11}).stroke({color:0xf0dc88,width:2}));const label=new Text({text:`${range}″`,style:{fill:0xf0dc88,fontFamily:"DM Mono",fontSize:11,fontWeight:"bold"}});label.anchor.set(.5);label.position.set(x,y-radius+10);add(new Graphics().roundRect(x-label.width/2-4,y-radius+2,label.width+8,label.height+4,3).fill({color:0x17251b,alpha:.88}));app.stage.addChild(label)})});
        if(s.ruler){add(new Graphics().moveTo(px(s.ruler.a.x),px(s.ruler.a.y)).lineTo(px(s.ruler.b.x),px(s.ruler.b.y)).stroke({color:0xf0dc88,width:2}));const label=new Text({text:`${(Math.hypot(s.ruler.a.x-s.ruler.b.x,s.ruler.a.y-s.ruler.b.y)*.36).toFixed(1)}″`,style:{fill:0xf0dc88,fontFamily:"DM Mono",fontSize:13}});label.anchor.set(.5);label.position.set(px((s.ruler.a.x+s.ruler.b.x)/2),px((s.ruler.a.y+s.ruler.b.y)/2));app.stage.addChild(label)}
        s.models.forEach(model=>{const x=px(model.x),y=px(model.y),radius=inches(baseDiameterInches(model)/2),g=new Graphics();g.circle(x,y,radius).fill(model.color).stroke({color:0xeeeeee,width:3});const radians=(model.rotation||0)*Math.PI/180;g.moveTo(x,y).lineTo(x+Math.sin(radians)*radius*.82,y-Math.cos(radians)*radius*.82).stroke({color:0x17251b,width:Math.max(2,radius*.13)});if(s.selected===model.id)g.circle(x,y,radius+6).stroke({color:0xf0dc88,width:3});g.eventMode="static";g.cursor="pointer";g.on("pointerdown",e=>{e.stopPropagation();s.onSelect(model.id);if(e.button===2)turn(model,e.nativeEvent);else if(e.button===0)drag(model,e.nativeEvent)});app.stage.addChild(g);const label=new Text({text:model.name[0],style:{fill:0x17251b,fontFamily:"DM Serif Display",fontSize:Math.max(10,radius*.8)}});label.anchor.set(.5);label.position.set(x,y);label.eventMode="none";app.stage.addChild(label)})
      };
      state.current.draw=draw;observer=new ResizeObserver(draw);observer.observe(host.current);draw();
    };start();return()=>{disposed=true;observer?.disconnect();app?.destroy(true,{children:true})}
  },[]);
  return <div ref={host} className={`board-canvas ${measuring?"measuring":""}`} style={{transform:`scale(${zoom})`}}/>;
}

function App(){const[models,setModels]=useState([]),[selected,setSelected]=useState(null),[circles,setCircles]=useState({}),[zoom,setZoom]=useState(1),[measuring,setMeasuring]=useState(false),[ruler,setRuler]=useState(null),[chargeId,setChargeId]=useState(null),sock=useRef();const model=models.find(m=>m.id===selected),send=message=>sock.current?.readyState===1&&sock.current.send(JSON.stringify(message));
  useEffect(()=>{const room=new URL(location).searchParams.get("room"),ws=sock.current=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}/socket${room?`?room=${room}`:""}`);ws.onmessage=({data})=>{const message=JSON.parse(data);if(message.models)setModels(message.models);if(message.roomId)history.replaceState({},"",`?room=${message.roomId}`)};return()=>ws.close()},[]);
  const update=(id,patch)=>setModels(current=>current.map(m=>m.id===id?{...m,...patch}:m)),move=(id,patch)=>{const current=models.find(m=>m.id===id);if(!current)return;update(id,patch);send({type:"move",id,x:patch.x,y:patch.y,rotation:current.rotation||0})},turn=(id,rotation)=>{update(id,{rotation});send({type:"rotate",id,rotation})},rotate=amount=>model&&turn(model.id,((model.rotation||0)+amount+360)%360);
  useEffect(()=>{const key=e=>{if(e.key.toLowerCase()==="c"&&model){setChargeId(id=>id===model.id?null:model.id);e.preventDefault();return}if(!model)return;const step=(e.shiftKey?.5:1)/BOARD_INCHES*100,r=(model.rotation||0)*Math.PI/180;if(e.key==="ArrowLeft")rotate(-15);else if(e.key==="ArrowRight")rotate(15);else if(e.key==="ArrowUp")move(model.id,{x:clamp(model.x+Math.sin(r)*step,2,98),y:clamp(model.y-Math.cos(r)*step,2,98)});else if(e.key==="ArrowDown")move(model.id,{x:clamp(model.x-Math.sin(r)*step,2,98),y:clamp(model.y+Math.cos(r)*step,2,98)});else return;e.preventDefault()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[model,models]);
  const values=model?circles[model.id]||[]:[];return <main><header><div><p>SHARED ONLINE TABLETOP</p><h1>Mistboard</h1></div><div>● Live board</div></header><section className="table"><div className="tools"><button className="control" onClick={()=>setZoom(z=>clamp(z-.2,.6,2.5))}>−</button><button className="control" onClick={()=>setZoom(z=>clamp(z+.2,.6,2.5))}>+</button><button className="control" onClick={()=>setZoom(1)}>Reset view</button><button className={`control ${measuring?"active":""}`} onClick={()=>{setMeasuring(v=>!v);setRuler(null)}}>{measuring?"Measuring":"Measure"}</button><CircleSelect disabled={!model} values={values} onChange={value=>setCircles(current=>({...current,[model.id]:value}))}/></div><PixiBoard models={models} selected={selected} circles={circles} chargeId={chargeId} measuring={measuring} ruler={ruler} zoom={zoom} onSelect={id=>{setSelected(id);if(!id)setRuler(null)}} onMove={move} onRotate={turn} onMeasure={next=>{if(next===undefined)setMeasuring(false);else setRuler(next)}}/></section><footer>{model?<><span>Selected: {model.name} · {Math.round(model.rotation||0)}° <select value={model.baseMm??30} onChange={e=>{const baseMm=Number(e.target.value);update(model.id,{baseMm});send({type:"base",id:model.id,baseMm})}}><option value="30">30 mm</option><option value="40">40 mm</option><option value="50">50 mm</option></select></span><span><button onClick={()=>rotate(-15)}>↶</button><button onClick={()=>rotate(15)}>↷</button></span></>:"Select a model"}<span>36″ × 36″</span></footer></main>}
createRoot(document.getElementById("root")).render(<App/>);
